apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-school-db-persistent-volume-claim
spec:
  volumeName: django-school-db-persistent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
