apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-school-db-persistent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: django-school-db-persistent-volume-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/VS/p2/database/persistent"

